"""add created_at to gps_raw

Revision ID: 2bf894143827
Revises: 96d37a084972
Create Date: 2026-07-27 21:23:13.233920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf894143827'
down_revision: Union[str, Sequence[str], None] = '96d37a084972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gps_raw', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gps_raw', 'created_at')
    # ### end Alembic commands ###
