"""initial schema

Revision ID: 424e78ff05ca
Revises: 
Create Date: 2026-06-28 10:03:52.434172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424e78ff05ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('org_users_user_id_org_id_key'), 'org_users', type_='unique')
    op.create_unique_constraint('unique_user_org', 'org_users', ['user_id', 'org_id'])
    op.create_index('idx_stoppages_location', 'stoppages', ['location'], unique=False, postgresql_using='gist')
    op.alter_column('vehicles', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index('idx_stoppages_location', table_name='stoppages', postgresql_using='gist')
    op.drop_constraint('unique_user_org', 'org_users', type_='unique')
    op.create_unique_constraint(op.f('org_users_user_id_org_id_key'), 'org_users', ['user_id', 'org_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
