"""add unique constraint on gps_raw vehicle_id and gps_time

Revision ID: 57bc075fc671
Revises: 16ff5a5247c8
Create Date: 2026-08-26 18:52:24.858189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57bc075fc671'
down_revision: Union[str, Sequence[str], None] = '16ff5a5247c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_vehicle_gps_time', 'gps_raw', ['vehicle_id', 'gps_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_vehicle_gps_time', 'gps_raw', type_='unique')
    # ### end Alembic commands ###
