"""add processed column to gps_raw and tripss

Revision ID: 8f882a30f179
Revises: c6472d0d656b
Create Date: 2026-07-27 20:24:11.180239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f882a30f179'
down_revision: Union[str, Sequence[str], None] = 'c6472d0d656b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gps_raw', sa.Column('processed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gps_raw', 'processed')
    # ### end Alembic commands ###
