"""add gps_matched table, update stoppage status

Revision ID: 9c41fbc515e9
Revises: 424e78ff05ca
Create Date: 2026-07-27 11:58:24.258769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c41fbc515e9'
down_revision: Union[str, Sequence[str], None] = '424e78ff05ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps_matched',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('gps_time', sa.DateTime(), nullable=False),
    sa.Column('route_distance_m', sa.Float(), nullable=True),
    sa.Column('trip_started_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('stoppages', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stoppages', 'duration_seconds')
    op.drop_table('gps_matched')
    # ### end Alembic commands ###
